name: VulnerabilityPatcher
version: "1.9.5"
api-version: "1.17"
main: me.cooljwb.vulnerabilitypatcher.VulnerabilityPatcher
authors: [CoolJWB]
description: Patches vulnerabilities that cause server instabilaty.
commands:
  vulnerabilitypatcher:
    aliases: [vp]
    description: The main command for VulnerabilityPatcher.
  getnbt:
    description: Reveals an items NBT data.
  getlag:
    description: Scans common sources for lag and reports back the most probable causes.